# Generated by Django 3.0.2 on 2020-06-07 09:54

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200605_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='article/%Y%m%d'),
        ),
    ]
